// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.VITE_PUBLIC_SUPABASE_URL || 'https://ngxvmmwqhpeqyfktdwvo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = process.env.VITE_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5neHZtbXdxaHBlcXlma3Rkd3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1ODg4OTgsImV4cCI6MjA3OTE2NDg5OH0.cUZDeQBHX4STZ1GrvaJlruW2YAb8dPV_MF1xtrWdkHY';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Make sure VITE_PUBLIC_SUPABASE_URL and VITE_PUBLIC_SUPABASE_ANON_KEY are set.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
 

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);